### ISSUE TITLE
Multibanco pending payments are marked as accepted in PrestaShop

### ISSUE THREAD

**Issue by jimmyn** [MONEI/MONEI-PrestaShop#17]
Payments with Multibanco are async, the user is shown the instructions to complete the payment in the ATM, but payment stays in `PENDING_PROCESSING` status. 

When payment is completed, MONEI will send the notification to the `callbackUrl` with the payment status. 

Make sure that the payment is marked as pending in PrestaShop until the payment status has changed to `SUCCEEDED` or `FAILED`

**Comment by jimmyn** [comment]
It looks like this issue is not solved

**Comment by presteamshop** [comment]
> It appears that this issue remains unresolved.
> 
> We need to ensure that the order status is updated whenever we receive a successful callback. For Multibanco payments, the first callback will indicate a PENDING_PROCESSING status, while the SUCCEEDED status is only notified once the customer completes the payment.
> 
> <img alt="image" width="1472" src="https://private-user-images.githubusercontent.com/5391775/342073415-6c6cef5f-389f-4174-84e7-a59e911e09e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyNDg3NzUsIm5iZiI6MTcxOTI0ODQ3NSwicGF0aCI6Ii81MzkxNzc1LzM0MjA3MzQxNS02YzZjZWY1Zi0zODlmLTQxNzQtODRlNy1hNTllOTExZTA5ZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMTcwMTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTljMTk0ZjUyYWU4NDZkNTg1OWQwYWViM2FkMmIyMWU5ZmEzZmQ4YjRjYTY5NTJjMmI2MjE5NWZjZmJhMzdjMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.RaM7YEer5YIo9LVLGZN17UDZ8_rAahfz1-Vm-zwD2vc">

Despues de varias pruebas, no he encontrado problema alguno con lo reportado. Veo que el código funciona bien, tanto como si se crea el pedido desde un inicio antes de hacer la redirección, como si se genera el pedido solo cuando es un pago exitoso.

Tocaría revisar la sonda/log dentro de Monei para esa transacción en especifico y saber la respuesta que ha dado el servidor de la tienda cuando se hizo el callback, es la unica manera de saber si hubo un error al comunicar el pago exitoso.
