### ISSUE TITLE
Payment confirmation step takes too long

### ISSUE THREAD

**Issue by jimmyn** [MONEI/MONEI-PrestaShop#29]
Whenever customer is redirected back to the store, we need to check the payment status by calling GET payment endpoint instead of waiting for the webhook.

![image](https://github.com/MONEI/MONEI-PrestaShop/assets/5391775/8a8e9056-61ea-4f6e-824a-1e138f598ae0)

**Comment by jimmyn** [comment]
@presteamshop Please make sure this works correctly, and the module is checking payment status using GET /payments/:id API endpoint and not waiting for the webhook

**Comment by presteamshop** [comment]
It has been confirmed that it works perfectly. As soon as the webhook confirms the payment, the popup completes the countdown and displays the payment OK message.

![image](https://github.com/MONEI/MONEI-PrestaShop/assets/48451631/c67216c7-d476-4299-82a5-9c426f7139b8)

**Comment by jimmyn** [comment]
@presteamshop we should not wait for the webhook at all, the module should check the payment status using GET /payments/:id API endpoint and not waiting for the webhook
